### ISSUE TITLE
information about this update 

### ISSUE THREAD

**Issue by zhtrb** [duytai/sNeu#3]
I‘ve noticed that you update this project. Can you tell me what you have made in this update briefly? Let me know the difference between latest version and last.

**Comment by duytai** [comment]
hi @zhtrb, I restructure the whole project. The general workflow is
- A rust program is instrumented and executed with AFL to collect test cases
- for each generated test case, it will be re-executed by sNeu to collect branch coverages and generate inputs, labels to train neural network
- while fuzzing, AFL asks neural network to know which bytes of the current test case is critical to mutate. Mutation is done in AFL and neural network is done in sNeu

There are some important files:

- nn.py : neural network and socket server to answer requests from AFL
- coverage.py: mutate test cases and generate input, label for training

I am currently writing a library to instrument Rust program because the current module:https://github.com/duytai/CompareCoverage is not compatible with a wide range of Rust programs

**Comment by zhtrb** [comment]
I wonder how can you use AFL to mutate. You mean you set the mutation strategy? But how? You also rewrite the program in AFL?

**Comment by duytai** [comment]
@zhtrb I do not rewrite AFL. I only add another mutation strategy
